default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= "chaitanya" %>
  password: <%= "abc123" %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>

development:
  <<: *default
  database: bus_booking_development

test:
  <<: *default
  database: bus_booking_test

production:
  <<: *default
  database: bus_booking_production